Repository life-librarians/life-bookshelf-client, pull requests merged in 2024-08, with the labels that each got.

#28 ✨ feat: 로그인/회원가입, n번째 채팅 api 연동 준비 및 보완
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main_app.dart
  lib/models/chat-n/autobiography_model.dart
  lib/services/chat-n/autobiography_service.dart
  lib/services/login/login_service.dart
  lib/services/register/register_service.dart
  lib/services/userpreferences_service.dart
  lib/viewModels/chat-n/autobiography_viewmodel.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/viewModels/register/register_viewmodel.dart
  lib/views/base/base_screen.dart
  lib/views/chat-n/autobiography_detail_chapter_screen.dart
  lib/views/chat-n/widget/after_fix.dart
  lib/views/chat-n/widget/before_fix.dart
  lib/views/chat-n/widget/during_fix.dart
  lib/views/home/home_screen.dart
  lib/views/login/login_screen.dart
  lib/views/register/register_screen.dart
Labels: feat

#30 ✨ feat: 온보딩 api 연동 준비 및 보완
  lib/models/mypage/mypage_model.dart
  lib/services/mypage/mypage_service.dart
  lib/services/onboarding/onboarding_service.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/onboarding/onboarding_screen.dart
Labels: bug, feat, fix

#33 Feat/#32 api2 - WIP
  ios/Podfile.lock
  lib/bindings/root_binding.dart
  lib/services/chatting/chatting_service.dart
  lib/services/home/chapter_service.dart
  lib/services/image_upload_service.dart
  lib/services/login/login_service.dart
  lib/services/onboarding/onboarding_service.dart
  lib/utilities/app_pages.dart
  lib/viewModels/chatting/chatting_viewmodel.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/publish/publish_viewmodel.dart
  lib/views/chatting/chatting_screen.dart
  lib/views/home/home_screen.dart
  lib/views/publish/publish_screen.dart
  pubspec.yaml
Labels: feat, fix

#35 ✨ fix: 온보딩 -> 메인 스크린 api 연동 보완
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Flutter_Plugins.xml
  assets/icons/main/example1.png
  assets/icons/main/example2.png
  assets/icons/main/example3.png
  ios/Podfile.lock
  lib/services/onboarding/onboarding_service.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/home/home_screen.dart
Labels: fix

#38 feat: 온보딩 임시 추가
  lib/services/onboarding/onboarding_service.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
Labels: bug
