Repository life-librarians/life-bookshelf-client, pull requests merged in 2024-07, with the labels that each got.

#14 ✨ feat: 로그인/회원가입 스크린 구현 완료
  .DS_Store
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  android/life_bookshelf_android.iml
  assets/icons/login/google_icon.svg
  assets/images/login/airplane.png
  assets/images/login/login.png
  assets/images/register/cloud_1.png
  assets/images/register/cloud_2.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/bindings/root_binding.dart
  lib/main.dart
  lib/models/login/login_model.dart
  lib/models/register/register_model.dart
  lib/services/chat-n/autobiography_service.dart
  lib/services/login/login_service.dart
  lib/services/register/register_service.dart
  lib/services/userpreferences_service.dart
  lib/utilities/font_system.dart
  lib/viewModels/chat-n/autobiography_viewmodel.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/viewModels/register/register_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/login/login_screen.dart
  lib/views/register/register_screen.dart
  lib/views/root/root_screen.dart
  pubspec.yaml
Labels: feat

#17 ✨ feat: 온보딩 페이지 구현 완료
  .DS_Store
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  assets/.DS_Store
  assets/images/AirplaneLoading.gif
  assets/images/cloud_1.webp
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/.DS_Store
  lib/bindings/root_binding.dart
  lib/models/onboarding/onboarding_model.dart
  lib/services/home/autobiography_service.dart
  lib/services/home/chapter_service.dart
  lib/services/mypage/mypage_service.dart
  lib/services/onboarding/onboarding_service.dart
  lib/utilities/color_system.dart
  lib/utilities/font_system.dart
  lib/viewModels/.DS_Store
  lib/viewModels/mypage/mypage_viewmodel.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/.DS_Store
  lib/views/home/home_screen.dart
  lib/views/mypage/.DS_Store
  lib/views/onboarding/.DS_Store
  lib/views/onboarding/components/cloud_window.dart
  lib/views/onboarding/components/date_field.dart
  lib/views/onboarding/components/disk_button.dart
  lib/views/onboarding/components/name_field.dart
  lib/views/onboarding/onboarding_screen.dart
  lib/views/root/root_screen.dart
  pubspec.yaml
Labels: feat

#18 Feat/#15 publication
  .DS_Store
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/utilities/color_system.dart
  lib/utilities/font_system.dart
  lib/viewModels/chatting/chatting_viewmodel.dart
  lib/viewModels/publish/publish_viewmodel.dart
  lib/views/base/base_screen.dart
  lib/views/chatting/chatting_screen.dart
  lib/views/publish/publish_screen.dart
  lib/views/publish/ticket.dart
  pubspec.yaml
Labels: feat

#20 ⚒️ fix: n-chat api 연동 로직 검토,수정
  .DS_Store
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  ios/Podfile.lock
  lib/models/chat-n/autobiography_model.dart
  lib/services/chat-n/autobiography_service.dart
  lib/services/userpreferences_service.dart
  lib/viewModels/chat-n/autobiography_viewmodel.dart
  lib/viewModels/register/register_viewmodel.dart
  lib/views/chat-n/autobiography_detail_chapter_screen.dart
  lib/views/chat-n/widget/before_fix.dart
  lib/views/chat-n/widget/during_fix.dart
  lib/views/home/home_screen.dart
  lib/views/register/register_screen.dart
  pubspec.yaml
Labels: fix

#22 ⚒️ fix: 마이페이지 api 연동(내 정보, 출판 상황), 내가 출판한 책 부분 모달 추가
  lib/services/mypage/mypage_service.dart
  lib/viewModels/mypage/mypage_viewmodel.dart
  lib/views/mypage/components/publication_progress.dart
  lib/views/mypage/mypage_screen.dart
Labels: fix

#23 fix: 온보딩 api 연동, 로컬 스토리지 저장 및 분기점 설정
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  ios/Podfile.lock
  lib/bindings/root_binding.dart
  lib/main.dart
  lib/main_app.dart
  lib/services/onboarding/onboarding_service.dart
  lib/viewModels/.DS_Store
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/.DS_Store
  lib/views/home/home_screen.dart
  lib/views/onboarding/components/cloud_window.dart
  lib/views/onboarding/components/date_field.dart
  lib/views/onboarding/components/name_field.dart
  lib/views/onboarding/onboarding_screen.dart
  lib/views/root/root_screen.dart
  pubspec.yaml
Labels: fix

#24 ⚒️ fix: RootBinding 오류 수정 & 마이페이지 api에 맞게 수정
  lib/.DS_Store
  lib/bindings/root_binding.dart
  lib/main.dart
  lib/main_app.dart
  lib/models/.DS_Store
  lib/models/home/chapter.dart
  lib/services/.DS_Store
  lib/services/home/chapter_service.dart
  lib/utilities/app_pages.dart
  lib/viewModels/.DS_Store
  lib/viewModels/home/home_viewmodel.dart
  lib/views/.DS_Store
  lib/views/home/home_screen.dart
Labels: fix

#26 ✨ feat: 출판 및 채팅 페이지 api 연결 준비
  ios/Podfile.lock
  lib/main.dart
  lib/models/chatting/conversation_model.dart
  lib/services/chatting/chatting_service.dart
  lib/services/image_upload_service.dart
  lib/utilities/app_pages.dart
  lib/viewModels/chatting/chatting_viewmodel.dart
  lib/viewModels/publish/publish_viewmodel.dart
  lib/views/chatting/chatting_screen.dart
  lib/views/home/home_screen.dart
  lib/views/publish/publish_screen.dart
  pubspec.yaml
Labels: feat, refactor
